JohanAgroFood/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Johan.Repository;
using Johan.DATA;

namespace JohanAgroFood.Controllers
{
    public class LoginController : Controller
    {
        private ILoginUserRepository loginRepository;

        //constructor
        public LoginController()
        {
            if (loginRepository==null)
            {
                this.loginRepository = new DLoginUserRepository(new JohanAgroFoodDBEntities());
            }
        }
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        // POST: Login
        //[Authorize]
        [HttpPost]
        public ActionResult Index(tblUser model, string returnUrl)
        {
            try
            {
                // TODO: Add insert logic here
                var lUser = loginRepository.GetUserById(model);
                if (lUser!=null)
                {
                    //FormsAuthentication.SetAuthCookie(model.USERNAME, false);
                    //var role = (SimpleRoleProvider)Roles.Provider;
                    //Roles.AddUserToRole(model.USERNAME, "Admin");
                    if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                        && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "ব্যবহারকারী অথবা পাসওয়ার্ড সঠিক নয়।");
                }
                return View();

            }
            catch
            {
                return View();
            }
        }

        // GET: Login/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Login/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Login/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Login/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Login/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Login/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Login/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

JohanAgroFood/Controllers/PartyController.cs
using Johan.DATA;
using Johan.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JohanAgroFood.Controllers
{
    public class PartyController : Controller
    {
       private IPartyRepository partyRepository;

        //constructor
       public PartyController()
        {
            if (partyRepository == null)
            {
                this.partyRepository = new DPartyRepository(new JohanAgroFoodDBEntities());
            }
        }
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public JsonResult SaveParty(tblParty party)
        {
            return Json(partyRepository.SaveParty(party),JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetParty()
        {
            var partyList = partyRepository.GetParty();
            return Json(partyList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult EditParty(tblParty objEditParty)
        {
            return Json(partyRepository.EditParty(objEditParty), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Delete(int pk)
        {
            return Json(partyRepository.Delete(pk),JsonRequestBehavior.AllowGet);
        }
    }
}

JohanAgroFood/Controllers/RiceController.cs
using Johan.DATA;
using Johan.Repository;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JohanAgroFood.Controllers
{
    public class RiceController : Controller
    {
        private IRiceRepository riceRepository;

        //constructor
        public RiceController()
        {
            if (riceRepository == null)
            {
                this.riceRepository = new DRiceRepository(new JohanAgroFoodDBEntities());
            }
        }
        // GET: Loaner
        public ActionResult RiceInfoIndex()
        {
            return View();
        }
        [HttpPost]
        public JsonResult SaveRiceInfo(tblSell riceInfo)
        {
            return Json(riceRepository.SaveRice(riceInfo), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EditRiceInfo(tblSell riceInfo)
        {
            return Json(riceRepository.EditRiceSell(riceInfo), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteRiceInfo(int pk)
        {
            return Json(riceRepository.DeleteRiceSell(pk), JsonRequestBehavior.AllowGet);
        }
           
        public JsonResult GetRiceInfo()
        {
            var sellList = riceRepository.GetRiceInfo();
            return Json(sellList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetStock()
        {
            var stkList = riceRepository.GetStock();
            return Json(stkList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadRice(int StockId)
        {
            List<tblProduct> rices = riceRepository.LoadRice(StockId);
            return Json(rices,JsonRequestBehavior.AllowGet);
        }
        public ActionResult rptRiceInfo()
        {
            return View();
        }

        //[HttpPost]
        public ActionResult Preview(string partyId, string from, string to)
        {
            try
            {
            LocalReport lr = new LocalReport();
            string path = Path.Combine(Server.MapPath("~/Reports"), "riceInfo.rdlc");
            if (!System.IO.File.Exists(path)||string.IsNullOrEmpty(partyId)||string.IsNullOrEmpty(from)||string.IsNullOrEmpty(to))
            {
                return View("rptRiceInfo");
            }
            else
            {
                lr.ReportPath = path;
            }
            tblSell riceRpt = new tblSell();
            riceRpt.partyId = Convert.ToInt32(partyId);
            riceRpt.fromDate = Convert.ToDateTime(from);
            riceRpt.toDate = Convert.ToDateTime(to);
            List<object> riceInfLst = riceRepository.GetRiceInfoRpt(riceRpt);
            //ReportDataSource rd = new ReportDataSource("sp_GetRiceInfo", riceInfLst);
            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "datset_GetProductInfo";

            reportDataSource.Value = riceInfLst;
            lr.DataSources.Add(reportDataSource);
            string reportType = "PDF";
            //string reportType1 = "Image";
           // string mimeType;
            string LastmimeType;
            string encoding;
            string fileNameExtension;

            string deviceInfo =

            "<DeviceInfo>" +
            "  <OutputFormat>" + reportType + "</OutputFormat>" +
            "  <PageWidth>8.5in</PageWidth>" +
            "  <PageHeight>11in</PageHeight>" +
            "  <MarginTop>0.5in</MarginTop>" +
            "  <MarginLeft>0.25in</MarginLeft>" +
            "  <MarginRight>0.25in</MarginRight>" +
            "  <MarginBottom>0.5in</MarginBottom>" +
            "</DeviceInfo>";

            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;
            renderedBytes = lr.Render(
                reportType,
                deviceInfo,
                out LastmimeType,
                out encoding,
                out fileNameExtension,
                out streams,
                out warnings);
            return File(renderedBytes, LastmimeType);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public FileContentResult GenerateAndDisplayReport(string bb)
        {
            LocalReport localReport = new LocalReport();
            string path = Path.Combine(Server.MapPath("~/Reports"), "riceInfo.rdlc");
            localReport.ReportPath = Server.MapPath("~/Reports/student.rdlc");
            List<WorldModel> customerList = new List<WorldModel>();
           
            customerList.Add(new WorldModel(){name="Europe", roll= "Sweden", country= "2001", year= "1823"});
            customerList.Add(new WorldModel() { name = "Europe", roll = "Sweden", year = "2002", country = "1234" });
            customerList.Add(new WorldModel() { country = "Europe", year = "Sweden", roll = "2003", name = "9087" });

            //customerList.Add(new WorldModel("Europe", "Denmark", "2001", "6793"));
            //customerList.Add(new WorldModel("Europe", "Denmark", "2002", "4563"));
            //customerList.Add(new WorldModel("Europe", "Denmark", "2003", "1897"));

            //customerList.Add(new WorldModel("Europe", "Norway", "2001", "5632"));
            //customerList.Add(new WorldModel("Europe", "Norway", "2002", "9870"));
            //customerList.Add(new WorldModel("Europe", "Norway", "2003", "2367"));

            //customerList.Add(new WorldModel("Asia", "India", "2001", "1980"));
            //customerList.Add(new WorldModel("Asia", "India", "2002", "9765"));
            //customerList.Add(new WorldModel("Asia", "India", "2003", "6789"));

            //customerList.Add(new WorldModel("Asia", "Japan", "2001", "9871"));
            //customerList.Add(new WorldModel("Asia", "Japan", "2002", "2987"));
            //customerList.Add(new WorldModel("Asia", "Japan", "2003", "1256"));

            //customerList.Add(new WorldModel("North America", "United States", "2001", "9871"));
            //customerList.Add(new WorldModel("North America", "United States", "2002", "9871"));
            //customerList.Add(new WorldModel("North America", "United States", "2003", "9871"));


            //customerList.Add(new WorldModel("North America", "Canada", "2001", "9871"));
            //customerList.Add(new WorldModel("North America", "Canada", "2002", "9871"));
            //customerList.Add(new WorldModel("North America", "Canada", "2003", "9871"));

            //customerList.Add(new WorldModel("North America", "Mexico", "2001", "9871"));
            //customerList.Add(new WorldModel("North America", "Mexico", "2002", "9871"));
            //customerList.Add(new WorldModel("North America", "Mexico", "2003", "9871"));

            //customerList.Add(new WorldModel("South America", "Brazil", "2001", "9871"));
            //customerList.Add(new WorldModel("South America", "Brazil", "2002", "9871"));
            //customerList.Add(new WorldModel("South America", "Brazil", "2003", "9871"));

            //customerList.Add(new WorldModel("South America", "Columbia", "2001", "9871"));
            //customerList.Add(new WorldModel("South America", "Columbia", "2002", "9871"));
            //customerList.Add(new WorldModel("South America", "Columbia", "2003", "9871"));

            //customerList.Add(new WorldModel("South America", "Argentina", "2001", "9871"));
            //customerList.Add(new WorldModel("South America", "Argentina", "2002", "9871"));
            //customerList.Add(new WorldModel("South America", "Argentina", "2003", "9871"));
            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "DataSet1";
            reportDataSource.Value = customerList;

            localReport.DataSources.Add(reportDataSource);
            string reportType = "Image";
            string mimeType;
            string encoding;
            string fileNameExtension;
            //The DeviceInfo settings should be changed based on the reportType            
            //http://msdn2.microsoft.com/en-us/library/ms155397.aspx            
            string deviceInfo = "<DeviceInfo>" +
                "  <OutputFormat>jpeg</OutputFormat>" +
                "  <PageWidth>8.5in</PageWidth>" +
                "  <PageHeight>11in</PageHeight>" +
                "  <MarginTop>0.5in</MarginTop>" +
                "  <MarginLeft>1in</MarginLeft>" +
                "  <MarginRight>1in</MarginRight>" +
                "  <MarginBottom>0.5in</MarginBottom>" +
                "</DeviceInfo>";
            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;
            //Render the report            
            renderedBytes = localReport.Render(reportType, deviceInfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
            //Response.AddHeader("content-disposition", "attachment; filename=NorthWindCustomers." + fileNameExtension); 
                return File(renderedBytes, "image/jpeg");
        }    
    }
}

JohanAgroFood/Controllers/UserController.cs
using Johan.DATA;
using Johan.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JohanAgroFood.Controllers
{
    public class UserController : Controller
    {
        private IUserRepository userRepository;

        //constructor
        public UserController()
        {
            if (userRepository == null)
            {
                this.userRepository = new DUserRepository(new JohanAgroFoodDBEntities());
            }
        }
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetUser()
        {
            var userList = userRepository.GetUser();
            return Json(userList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SaveUser(tblUser user)
        {
            return Json(userRepository.SaveUser(user),JsonRequestBehavior.AllowGet);
        }
        public JsonResult Edit(tblUser objUser)
        {
            return Json(userRepository.Edit(objUser), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Delete(int pk)
        {
            return Json(userRepository.Delete(pk), JsonRequestBehavior.AllowGet);
        }
    }
}

JohanAgroFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app='johanApp'>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>সেলস ম্যানেজমেন্ট সফটওয়্যার</title>

    @*css files*@
    @Styles.Render("~/Content/css")
    <link href="~/Assets/css/style.css" rel="stylesheet" />
    <link href="~/Assets/css/jquery-ui-1.11.4.css" rel="stylesheet" />
    <link href="~/Assets/libs/UiGrid/ui-grid-unstable.css" rel="stylesheet" />

    @*3rd party libraries*@
    <script src="~/Assets/js/jquery-1.10.2.min.js"></script>
    <script src="~/Assets/libs/angular-1.3.14/angular.min.js"></script>
    <script src="~/Assets/libs/angular-1.3.14/angular-route.js"></script>
    <script src="~/Assets/js/jquery.validate.min.js"></script>
    <script src="~/Assets/js/jquery-ui-1.11.4.js"></script>
    <script src="~/Assets/libs/angular-1.3.14/angular-animate.min.js"></script>
    <script src="~/Assets/libs/UiGrid/ui-grid-unstable.js"></script>
    @Scripts.Render("~/bundles/modernizr")

    @*custom jquery files*@
    <script src="~/App/app.js"></script>
    <script src="~/App/Shared/Services/baseDataSvc.js"></script>
    <script src="~/App/Shared/Services/convertSvc.js"></script>
    <script src="~/App/Shared/Directives/Validation.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("জোহান এগ্রো ফুড", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("হোম", "Index", "Home")</li>
                    <li class="dropdown">
                        <a aria-expanded="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">স্টক ম্যানেজমেন্ট<span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li>@Html.ActionLink("স্টক সমূহ", "StockIndex", "Stock")</li>
                            <li><a href="/#">ধানের স্টক</a></li>
                            <li>@Html.ActionLink("প্রোডাক্টের স্টক", "ProductStock", "Stock")</li>
                            <li>@Html.ActionLink("ক্ষুদের স্টক", "ParticleStock", "ParticleSell")</li>
                            <li>@Html.ActionLink("জের স্থানান্তর", "BalanceIndex", "BalanceTransfer")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a aria-expanded="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">রিপোর্ট<span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="/#">ধানের রিপোর্ট</a></li>
                            <li>@Html.ActionLink("প্রোডাক্টের রিপোর্ট", "rptRiceInfo", "Rice")</li>
                            @*<li>@Html.ActionLink("ক্ষুদের রিপোর্ট", "rptParticleInfo", "ParticleSell")</li>*@
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a aria-expanded="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">বিক্রয় সমূহ <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li>@Html.ActionLink("চাল বিক্রয়", "RiceInfoIndex", "Rice")</li>
                            <li>@Html.ActionLink("তুষ বিক্রয়", "HuskInfoIndex", "HuskSell")</li>
                            <li>@Html.ActionLink("ক্ষুদ বিক্রয়", "ParticleInfoIndex", "ParticleSell")</li>
                            <li>@Html.ActionLink("ধান গ্রহণ", "PaddyInfoIndex", "Paddy")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a aria-expanded="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">খাত সমূহ <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li>@Html.ActionLink("খরচের খাত", "ConsumptionIndex", "Consumption")</li>
                            <li>@Html.ActionLink("ইনকামের খাত", "IncomeIndex", "Income")</li>
                            <li>@Html.ActionLink("বাকির খাত", "Index", "DuePayment")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a aria-expanded="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">বেসিক সেটআপ <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li>@Html.ActionLink("বাবহারকারী", "Index", "User")</li>
                            <li>@Html.ActionLink("পার্টি", "Index", "Party")</li>
                            <li>@Html.ActionLink("লোনার", "LoanerIndex", "Loaner")</li>
                            <li>@Html.ActionLink("খাত", "SectorIndex", "Sector")</li>
                            <li>@Html.ActionLink("জোন", "zone", "Sector")</li>
                            <li>@Html.ActionLink("জেলা", "district", "Sector")</li>
                            <li>@Html.ActionLink("প্রোডাক্ট", "ProductIndex", "Product")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("আমাদের সম্পর্কে", "About", "Home")</li>
                    @*<li>@Html.ActionLink("যোগাযোগ", "Contact", "Home")</li>*@

                    <li>@Html.ActionLink("সাইন আউট", "Login", "Login")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><img src="~/Assets/images/logo.jpg" /> </li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content" style="min-height:400px;">
        @RenderBody()

    </div>
    <hr />
    <footer>
        <div>
            <div class="col-md-6 col-md-offset-4">
                <p>&copy; @DateTime.Now.Year - Development By Johan Group</p>
            </div>
        </div>

    </footer>

    @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>